name = ['lhl','yb','zsh','yh','my']
print(name[0]+" "+"invited"+ " "+name[1]+" "+" "+name[2]+" "+name[3]+" "+name[4]+" "+"to have dinner")
print(name[4]+' '+"took time off on business")
name[4] = 'tmc'
print(name)
print(name[0]+" "+"invited"+ " "+name[1]+" "+" "+name[2]+" "+name[3]+" "+name[4]+" "+"to have dinner")
print("I found a bigger table")
name.insert(0,'ltk')
name.insert(3,'dyc')
name.append('dzz')
print(name)
print(name[0]+" "+"invited"+ " "+name[1]+" "+" "+name[2]+" "+name[3]+" "+name[4]+" "+name[5]+" "+name[6]+" "+name[7]+" "+"to have dinner")
print("I can only invited two guests to dinner")
guest1 = name.pop()
print(guest1+" "+"I\'m sorry I cant\'t invited you")
guest2 = name.pop()
print(guest2+" "+"I\'m sorry I cant\'t invited you")
guest3 = name.pop()
print(guest3+" "+"I\'m sorry I cant\'t invited you")
guest4 = name.pop()
print(guest4+" "+"I\'m sorry I cant\'t invited you")
guest5 = name.pop()
print(guest5+" "+"I\'m sorry I cant\'t invited you")
guest6 = name.pop()
print(guest6+" "+"I\'m sorry I cant\'t invited you")
print("I invited"+" "+name[0]+" "+"to come")
print("I invited"+" "+name[1]+" "+"to come")
print(name)
del name[0]
del name[1]
print(name)